name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - run: rustc -V
      - run: rustup -V
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
